### ISSUE TITLE
permit specifying a multi-level name

### ISSUE THREAD

**Issue by davidelang** [rsyslog/liblognorm#105]
allow a fieldname to be specify multiple levels

i.e. [%source!ip:ipv4%]:%source!port:char-to:-%-

creates 'source: { ip: "value", port: "value"}'

Since this is part of the basic fieldname, it should work in a v1 syntax as well as v2 syntax (it's not dependent on the extradata and options that are JSON in v2 syntax

**Comment by rgerhards** [comment]
That's a pretty complex beast given the recursive nature of the parser. It means we need to differentiate between the parsing step and the final name assignment. That's probably post the initial v2 version.

Does it really make sense to do this in liblognorm? I mean it would need to do the same thing you can also do in rsyslog, namely moving the items to a different name space.

**Comment by davidelang** [comment]
> Does it really make sense to do this in liblognorm? I mean it would need to do the same thing you can also do in rsyslog, namely moving the items to a different name space.

This is something that you want to do on a per-rule level.

for example, when parsing cisco logs, we use cisco-interface-spec to create the structure:
src:{ip,port,user}

now there's another log message 
%ASA-6-602101: PMTU-D packet 1469 bytes greater than effective mtu 1426, dest_addr=10.51.50.42, src_addr=10.1.50.13, prot=UDP
or
%ASA-4-402116: IPSEC: Received an ESP packet (SPI= 0x976FCAFA, sequence number= 0x60FC8) from 76.79.249.222 (user= 76.79.249.222) to 152.186.34.101.  The decapsulated inner packet doesn't match the negotiated policy in the SA.  The packet specifies its destination as 10.1.50.37, its source as 192.168.10.1, and its protocol as icmp.  The SA specifies its local proxy as 10.1.0.0/255.255.0.0/ip/0 and its remote_proxy as 192.168.99.0/255.255.255.0/ip/0.

I really want to have the source as src:{ip} not src_ip 
There are examples that list user, ip, port as very clearly different fields in the log messages, but I want to have all the source IP addresses as src:{ip}


As an initial cut, you could have a post-parse pass that looks for any field names with ! in them and move them afterwords.

I don't see any way to do this in rsyslog rules without having tons of special cases.

**Comment by rgerhards** [comment]
I see where you are coming from and it makes a lot of sense. I think we need to do this as a post processing step as the json is dynamically build from bottom to top during parsing. So we do not know all data elements before we are done. Also if we directly would modify elements outside the current scope (if we could), we would get into big trouble when we need to backtrack. Trying to solve this would be pretty complex and probably even slower than a post processing step. 

I will probably implement this shortly after the first v2 release.
