### ISSUE TITLE
v2 reading v1 files handles some errors differently

### ISSUE THREAD

**Issue by davidelang** [rsyslog/liblognorm#129]
if v1 reads a bad config line, it throws everything away when it hits the \n

with v2 reading a v1 config (no version=2), if you have an extra % in a line, the newline now becomes part of a parser definition and you skip a lot of lines in the rulefile before things happen to even out again.

Ideally this would report an error, but this is messy to add to each parser. It's probably better off as a pre-pass to check the odd/even state of % on a non-comment line and 'fix' it by adding a trailing % if there are an odd number of them (and showing an error), the rule won't work, but it didn't work before.

**Comment by rgerhards** [comment]
Its a feature to have line breaks in parser definitions. Check the test
bench.

Sent from phone, thus brief.
Am 07.08.2015 22:23 schrieb "davidelang" <notifications@github.com>:

**Comment by davidelang** [comment]
in v2 mode it's a feature, in v1 mode it's a behavior change.

I had a half dozen such lines in my 800 line rulebase (3x char-to that weren't 
closed out, 3x $something%) but the result was rather hard to track down.

David Lang

**Comment by rgerhards** [comment]
This was introduced in 1.1.2.

Sent from phone, thus brief.
Am 07.08.2015 22:49 schrieb "davidelang" <notifications@github.com>:

**Comment by davidelang** [comment]
hmm, I wonder how I got away with so much broken since it came out. I've got a 
nightly report that shows me all logs that didn't get parsed that day. With the 
breakage I had, a LOT of stuff should have been failing.

the following should show a list of all broken lines (and the final grep nicely 
highlights the % if you are outputting to a text console)

grep -f '^#' rulebase |sed -e s/'[^%]'//g -e s/'%%'//g |grep -n % |cut -f 1 -d : 
|while read line; do grep -v '^#' rulebase |head -$line |tail -1 |grep %; done

David Lang

**Comment by rgerhards** [comment]
I thought a bit about this. I think I can implement some logic that checks continuation lines and emits warnings if they start with "rule=". That should handle all such occurences. I can't give a hard error as this could be legit, but I think a warning should be sufficient to guide that admin. What do you think?

**Comment by davidelang** [comment]
I would make line continuation where the new line starts with rule= a hard error and document it in the section that says mult-line rules are allowed. There is never a case where a multi-line rule _must_ be split at that point, and disallowing it will do wonders for detecting broken configs.

I think this is valuable enough to change in the v1 codebase as well, even if it means making a 1.1.3 with no other changes.

**Comment by rgerhards** [comment]
@davidelang I have implemented it in the way you suggested. It really make very little sense to have ```rule=``` on a continuation line...
