### ISSUE TITLE
problem with v2 repeat parser compared to tokenized

### ISSUE THREAD

**Issue by davidelang** [rsyslog/liblognorm#130]
I have the log message:

Aug 18 13:18:45 192.168.99.2 %ASA-6-106015: Deny TCP (no connection) from 173.252.88.66\/443 to 76.79.249.222\/52746 flags RST  on interface outside

with v1 it parses with

prefix=%timestamp:date-rfc3164% %hostname:word%
rule=cisco,fwblock: \x25ASA-6-106015\x3a Deny %proto:word% (no connection) from %source:cisco-interface-spec% to %dest:cisco-interface-spec% flags %flags:tokenized: :word%  on interface %srciface:word%

with v2 I tried:

prefix=%timestamp:date-rfc3164% %hostname:word%
rule=cisco,fwblock: \x25ASA-6-106015\x3a Deny %proto:word% (no connection) from %source:cisco-interface-spec% to %dest:cisco-interface-spec% flags %flags:repeat{ "parser": {"type":"word", "name":"."}, "while":{"type":"literal", "text":" "} }%  on interface %srciface:word%

and it fails.

It fails because in v1 the double space doesn't match word so the array created for flags is flags: [ "RST" ] and then the rest matches the literal "  on interface "

with v2, the repeat parser ends up creating the array: flags: [ { ".": "RST" }, { }, { ".": "on" }, { ".": "interface" }, { ".": "outside" } ] and then when it backtracks, it drops the entire repeat instead of 'popping' items out of the array.

If it fails when it hits the empty array, that would match the v1 behavior and allow this to work. The better thing would be if there was a way to recognize cases where a parser may need to be less greedy than default in order to match the rest of the constraints on the line.

As it is, I don't see any way to create a v2 rule that works when there are multiple flags there (multiple flags are space separated with an extra space after all the flags.

**Comment by rgerhards** [comment]
I think the tokenized parser did not work correctly here. If there is a mismatch during parsing some element that should exist, the whole parser must fail. Anyhow, I see where you are coming from and think it is useful to add an option to repeat to permit sucessfully terminating the parser even when the mismatch occurs during the inner execution.

I tried to reproduce the issue based on the posting, but it looks like github has changed some elements. Do I correctly understand that the source message contains a double space after RST (so ```RST<SP><SP>```)? I ask because there is only one in the posting above. If I change that to double space, I get to an array similar to yours. The resulting ```{}``` really does not look right. If word does not match, the parser should immediately bail out.

However, that correct behaviour would lead to the same result that you see currently. Question now: if we permit the repeat parser to accept mismatches in mandatory elements as successful termination condition, where should the parser pointer be in that case? At the start of the unparsed element? And what should happen if there is a sequence of parser and one of them does not match? IIRC this would be a pretty complex case.

The use case here is that you have a list of space-delimited words, which is terminated **not** by a non-space but rathe a sequence of two spaces. Is that correct? If so, there maybe is a better and more consistent way to handle such cases than be permitting fail inside the mandatory part.

**Comment by davidelang** [comment]
yes, github must have 'cleaned' things.

with tokenized, if 'word' doesn't match or the separator doesn't match things end
with releated, it looks like things continue until the separator doesn't match and if the parser doesn't match you end up with an empty element.

my guess is that whenthe parser doesn't match it ails out, but the error doesn't get propogatedup to the repeated wrapper, so it continues.

with the input:
  foo<sp>tag1<sp><tag2><sp><sp>bar<sp>baz
in v1
  rule=:foo%flags:tokenized:<sp>:word%<sp><sp>bar<sp>baz
will create the array flags:['tag1','tag2"]

in v2
  rule=:foo%tags:repeat{"parser": {"type":"word", "name":"."}, "while":{"type":"literal", "text":"<sp>"} }%<sp><sp>bar<sp>baz 
will create the array flags:[{'.':'tag1'}, {'.':tag2'}, {}. {'.','bat'}, {'.':'baz'}]

not bailing out is one problem. The other problem is how to get an array of just the tags rather than an array of objects?

[quote]However, that correct behaviour would lead to the same result that you see currently. Question now: if we permit the repeat parser to accept mismatches in mandatory elements as successful termination condition, where should the parser pointer be in that case? [/quote]
it should point at the first character after the separator following the last complete success.

so if you were to do
type=suffix:mb
type=suffix:kb
rule=:%values:repeated{ 'parser': [ {'name': 'value' 'type': 'word'},
                                                        {'type':'literal', 'text':' '},
                                                        {'name':'suffix', 'type'='@suffix'}
                                                     ],
                                          'while':{ 'type': 'literal', 'text':':'}
                                        }%

25 kb -> values:[{'value':25', 'suffix':'kb'}]
25 kb: -> values:[{'value':25', 'suffix':'kb'}] unparsed ':'
25 kb:50 mb -> values:[{'value':values:[{'value':25', 'suffix':'kb'}, {'value':50', 'suffix':'mb'}]
25 kb:50 gb -> values:[{'value':25', 'suffix':'kb'}] unparsed ':50 gb'

[quote]The use case here is that you have a list of space-delimited words, which is terminated not by a non-space but rather a sequence of two spaces. Is that correct? If so, there maybe is a better and more consistent way to handle such cases than be permitting fail inside the mandatory part.[/quote]
you are going to have failures inside the mandatory part in many cases. that data should not just vanish. When you hit a missmatch, you need to back up to the beginning of the loop.

I also think that with repeating items, you need to be able to back up through the loop for other reasons.

for example, if there is a line that didn't have the double spaces after the list, something like

error X with flags a b c happened on server Y

 (where a b c represent one or more flags) you shoudl be able to use a rule along the lines of

type=spaced_flags:%flags:repeat{ "parser": {"type":"word", "name":"."}, "while":{"type":"literal", "text":" "} }% 
rule=:error %error:word% with flags %flags:@spaced_flags% happened on server %server:word%

in it's first pass, liblognorm would create
  array ['a','b','c','happened','on','server','Y']
  unparsed ''
and find that no rule matches, it would then back up one loop and try with
  array ['a','b','c','happened','on','server']
  unparsed ' Y'
and keep going until it got to 
  array ['a','b','c']
  unparsed ' happened on server Y'
at which point it would now find that there is a rule that matches the rest of it.

I agree that logs like this are bad formatting , but lists like FLAGS [a b c] are rather common, and well delineated, but not handled well by the current repeated parser.

**Comment by rgerhards** [comment]
There definitely is a bug inside the parser in that it indeed does not check the sub-parsers return value.

**Comment by rgerhards** [comment]
I'll address this in two steps: first I fix the bug, which will make the parser not pass at whole. Next, I'll add an option to support mismatches in the while part. So this can be enabled for those cases where it is required.

**Comment by rgerhards** [comment]
Implementation of step 2 brings up this here (to be adressed later): https://github.com/rsyslog/liblognorm/issues/140
