### ISSUE TITLE
add an option to put the rule template as a variable in the output

### ISSUE THREAD

**Issue by davidelang** [rsyslog/liblognorm#134]
As I'm going through and creating rules to cover startup messages and similar, I find I have a lot of messages that I want to match and classify as startup, but have little or nothing to parse from them.

While I could give each one a unique tag and then annotate the tag, it seems like it would be better to create a variable that holds the rule.

I would suggest that everything after the initial : be put in the variable, but with any parsed elements collapsed down to just the name

so for a rule like: 
prefix=%timestamp:date-rfc3164% %hostname:word%
rule=cisco,disconnect: \x25ASA-6-302018\x3a Teardown GRE connection %connectionid:number% from %source:cisco-interface-spec% to %dest:cisco-interface-spec% duration %duration:word% bytes %bytes:number%

the variable would contain
 \x25ASA-6-302018\x3a Teardown GRE connection %connectionid% from %source% to %dest% duration %duration% bytes %bytes%
or
%timestamp% %hostname% \x25ASA-6-302018\x3a Teardown GRE connection %connectionid% from %source% to %dest% duration %duration% bytes %bytes%

it may make sense to make it optional to show the prefix or not.

**Comment by rgerhards** [comment]
I think I don't fully understand the requirement. Do you want each match to contain the rule that matched as part of the json being returned?

On the prefix: please note that it is not natively available inside the parse DAG. It's only visible during rulebase parsing. It might get messi to track it if multiple prefix definitions are used.

**Comment by davidelang** [comment]
yes, I want an option to include the rule being matched as part of the JSON returned by the match

not including the prefix is fine

per-rule annotation (as opposed to per-tag annotation) could satisfy this need as well, at the cost of a far more complicated config file

there's good value in being able to see both the log template and the values at the same time. it's slightly different, but largely overlapping value with per-rule annotations.


There is some way that you store the tags related to the line with the rule ending point.  This would store a simplified version of the rule the same way.

**Comment by rgerhards** [comment]
I have added an option to create a mockup of the rule. I can't add the exact rule, because I don't always have it at runtime (e.g in cases with user-defined types). The current implementation also includes the field name, but it is esay to ignore that in your scripts, where I see clear need in some other use cases. We could make that option more granular in lager cases, as well. Just want to get the bare basics into it.

**Comment by davidelang** [comment]
I don't see this mentioned in the docs when I just looked for it.
