### ISSUE TITLE
v2: re-name ln_loadRulebase back to ln_loadSample?

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/liblognorm#139]
It looks like the semantics are the same again. As we now also support v1 rule bases, it sounds like the right thing to do, because that means the majority of applications do not necessarily need a source code change -- only APIs used by very few apps are modified in v2, now.

Evaluate if that is possible. Note that a new soname major version is still needed because we have removed some APIs.

**Comment by rgerhards** [comment]
ok, it looks like I already did this back in July... ;)

**Comment by davidelang** [comment]
so that's why rsyslog is able to work with the new version :-)
what APIs are changed/removed at this point?

**Comment by rgerhards** [comment]
from the compatibilty doc:

```
 * ln_loadSample() does no longer exist
    loading of samples at runtime is no longer possible. This is due to
    the fact that the parse DAG is compiled into the most efficient form
    and thereafter read-only. If urgently needed, we could change the code
    so that the unoptimized form is kept (memory intense) and a re-compile
    happens after each addition (time intense).
```
