### ISSUE TITLE
rfc3339 formatting of $!timestamp

### ISSUE THREAD

**Issue by alecswan** [rsyslog/liblognorm#176]
What do I need to do to make timestamp attribute show up as rfc3339 formatted date in the JSON produced by mmnormalize in the following rsyslog config? The following produces JSON with "timestamp": "Nov 19 02:11:01" attribute.

set $!timestamp = $timereported;
action(type="mmnormalize"
        rulebase="/etc/rsyslog.d/rules/myrule.rb"
)

Thanks

**Comment by davidelang** [comment]
the date formatting would happen when you used the resulting variable, not when you create it. look at the property formatting options http://www.rsyslog.com/doc/v8-stable/configuration/property_replacer.html

**Comment by alecswan** [comment]
My problem was that it wasn't clear how to combine formatted timestamp property with mmnormalize $!all-json. I found the answer in https://github.com/rsyslog/rsyslog/issues/85. It looks strange that I have to explicitly open curly brace but not close. It would be nice if this was documented somewhere.
```
template(name="cee-syslog"
type="list") {
constant(value="{")
constant(value="\"@timestamp\":\"") property(name="$!timereported")
constant(value="\",") property(name="$!all-json" position.from="2")
}
```

Thanks

**Comment by alecswan** [comment]
This is not a liblognorm issues, so closing it.
