### ISSUE TITLE
Segfault parsing an alternate field

### ISSUE THREAD

**Issue by mostolog** [rsyslog/liblognorm#220]
Hi
Trying to parse an apache access message:
> echo "1.2.3.4 - - [23/Sep/2016:11:12:50 +0200] \"GET /app/img/oldlogo.png HTTP/1.1\" 304 -" | /usr/lib/lognorm/lognormalizer -r /rule.rb

**rule.rb**
```
version=2
# Trying to parse APACHE ACCESS
rule=:%host:ipv4% %{"type":"alternative","parser":[{"type":"literal","text":"-"},{"type":"word","name":"identd"}]}% %r:rest%
```
**I'm getting: Segmentation fault (core dumped)**

Ubuntu 16.04 running rsyslogd 8.22.0, compiled with:
	PLATFORM:				x86_64-pc-linux-gnu
	PLATFORM (lsb_release -d):		
	FEATURE_REGEXP:				Yes
	GSSAPI Kerberos 5 support:		No
	FEATURE_DEBUG (debug build, slow code):	No
	32bit Atomic operations supported:	Yes
	64bit Atomic operations supported:	Yes
	memory allocator:			system default
	Runtime Instrumentation (slow code):	No
	uuid support:				Yes
	Number of Bits in RainerScript integers: 64

**Comment by mostolog** [comment]
```
rule=:%[
	{"type":"ipv4", "name":"ip"},
	{"type":"literal", "text:" "},
	{"type":"literal", "text:"-"},
	{"type":"rest", "name":"r"}
]%
```

Neither works.

**Comment by mostolog** [comment]
Possible duplicate of #153

**Comment by rgerhards** [comment]
I can reproduce this.

**Comment by rgerhards** [comment]
This is related to the literal not having a name. So a work-around is to assign a name to it.

**Comment by mostolog** [comment]
You mean   {"type":"literal", "text":"", "name":"whatever"},?

**Comment by rgerhards** [comment]
2016-10-17 12:01 GMT+02:00 mostolog <notifications@github.com>:

> You mean {"type":"literal", "text":"", "name":"whatever"},?
>

Yes

I think duplicate names are not checked, but than it is undefined which
value persists (probably not of interest here).

**Comment by rgerhards** [comment]
It looks like the problem is that we try to compact a literal parser with multiple refcount. This cannot be done as obviously multiple path lead to that parser. Seems like that predicate was not checked.

**Comment by mostolog** [comment]
Thanks for fixing. Should I test or can I wait to v8.23 ?

**Comment by rgerhards** [comment]
Testing would be appreciated. I plan to release liblognorm 2.0.2 shortly.

Rainer

2016-10-17 17:52 GMT+02:00 mostolog <notifications@github.com>:
