### ISSUE TITLE
Numbers are returned as strings in the generated JSON instead of like, actual, numbers

### ISSUE THREAD

**Issue by itkovian** [rsyslog/liblognorm#250]
~~~~
rule=foo:foo %id:number%
rule=bar:%[
    {"type": "literal", "text": "bar "},
    {"type": "number", "name": "id"}
    ]%
~~~~

generates the following result by running `lognormalizer -r files/mmnormalize_rules.rb`

~~~~
foo 4
{ "id": "4" }
bar 3
{ "id": "3" }
~~~~

I would have expected to get e.g. `{"id": 4}` and `{"id": 3}` instead. Any particular reason this is not done, or am I missing something?

**Comment by davidelang** [comment]
everything that liblognorm returns is strings.

There is (or was) an ability to explicitly change a specific field, but that's 
actually as likely to cause other problems down the road where things try to 
compare strings to numbers and fail.

David Lang

**Comment by itkovian** [comment]
Cause problems for liblognorm itself? Or for tools processing the information? My end goal is to push structured data into elasticsearch and it is nice that the values there are in their native data type, i.e., ints, floats and such.

**Comment by davidelang** [comment]
in downstream processing. Think of cases like response codes in Apache logs that 
are numbers or the sting '-'. This sort of things is extremely common, and 
rsyslog treats everything as a string (unless you are doing math on it)

**Comment by itkovian** [comment]
OK, thanks for your swift answer.

**Comment by davidelang** [comment]
as I said, there is (or was) a way to configure the rule to change this for an 
individual field, but I'd have to dig through the documentation for it.

**Comment by itkovian** [comment]
I found this in the examples

~~~~
reset_rules
add_rule 'rule=:gc pause: %pause_time:interpret:float:float%ms'
execute 'gc pause: 12.3ms'
assert_output_json_eq '{"pause_time": 12.3}'
~~~~

But it does not seem to work:
~~~~
rule=foo:foo %id:interpret:int:number%
~~~~
gives
~~~~
liblognorm error: rulebase file files/mmnormalize_rules.rb[23]: invalid field type 'interpret'
~~~~

Version:

~~~~
lognormalizer version: 2.0.4.master
liblognorm version: 2.0.4.master
~~~~

**Comment by itkovian** [comment]
Looking through the code, this seems to be for the parser v1.

~~~~
typedef enum interpret_type {
        /* If you change this, be sure to update json_type_to_name() too */
        it_b10int,
        it_b16int,
        it_floating_pt,
        it_boolean
} interpret_type;
~~~~

Documentation has:

The v2 engine understands almost all v1 parsers, and most importantly all
that are typically used. It does not understand these parsers:

 * tokenized
 * recursive
 * descent
 * regex
 * interpret
 * suffixed
 * named_suffixed

The recursive and descent parsers should be replaced by user-defined types
in. The tokenized parsers should be replaced by repeat. For the others,
currently there exists no replacement, but will the exception of regex,
will be added based on demand.

So, will there be any plans to add this?
