### ISSUE TITLE
Unable to use string-to

### ISSUE THREAD

**Issue by kutsav** [rsyslog/liblognorm#260]
Can anyone give a sample syntax for using "string-to"?

I have a string like: [ip] Text is here [file asdad]
I want to get "Text is here" field, unable to parse this

**Comment by davidelang** [comment]
rule=:[%ip:ipv4%] %something:string-to:[%[file %filename:string-to:]%]

> I have a string like: [ip] Text is here [file asdad]
> I want to get "Text is here" field, unable to parse this
>
>

**Comment by utsav2307** [comment]
i tried using string-to. Doesnt work
