### ISSUE TITLE
Unparsed-data:"" issue

### ISSUE THREAD

**Issue by joaoantoniopereira** [rsyslog/liblognorm#261]
Hello,
I am trying to do the log  -> rsyslog(mmnormalize) -> elasticsearch pipeline

This is my log:
Oct 29 09:47:08,john,65,lawyer

This is my .conf file

module(load="imfile")
module(load="mmnormalize")
module(load="omelasticsearch")

input(type="imfile"
      File="/opt/log/test.log"
      Tag="logging"
)

action(type="mmnormalize"
  rulebase="/opt/rsyslog/rule.rb"
  useRawMsg="on"
)

template(name="lumberjack" type="list"){
  property(name="$!all-json")
}

action(type="omelasticsearch"
  template="lumberjack"  # use the template defined earlier
  searchIndex="test"
  searchType="events"
  server="localhost"
  serverport="9200"
  bulkmode="on"  # use the bulk API
  action.resumeretrycount="-1"  # retry indefinitely if Logsene/Elasticsearch is unreachable
)

This is my .rb file
version=2
rule=syslog:%date1:date-rfc3164%,%name:word%,%age:number%,%job:word%

In the Elasticsearch output I get unparsed-data:"" but is does not separate the fields as I needed.
originalmsg:Oct 29 09:47:08,john,65,lawyer unparsed-data: _id:AV7AjNiu8vEqtkzBSJbQ _type:events _index:test _score:1

Does anyone know what am I doing wrong?
Thanks!

**Comment by davidelang** [comment]
did you solve your problem or give up?

This error usually happens when you run out of input line before reaching the 
end of any rules that have matched up to this point.

the command line parser lets you do a debug mode so you can see exactly what's 
happening.

**Comment by aspyct** [comment]
Same issue for me here, I end up with an empty `unparsed-data`, but no field is extracted. I have almost the same rule just above the one that fails, and that one works perfectly fine.

 @joaoantoniopereira , did you solve the issue? What was your solution?

**Comment by davidelang** [comment]
unparsed-data="" can mean that you ran out of line to parse while the rule still 
requires more characters, so the rule doesn't match, but you have no unparsed 
data left.

David Lang

**Comment by aspyct** [comment]
Hi @davidelang , sorry for forcing you to repeat yourself. I modified the rule and somehow fixed the issue. I'm still not sure that was the problem you explain, unless something was hiding at the end of my rule that I couldn't see.

Anyway, the only advice that I could give to other people who land here is: iterate on your rules using `lognormalizer -r rules.rb`, piece by piece.

**Comment by joaoantoniopereira** [comment]
Hi,
I was messing around with rsyslog some years ago. I manage to do a little parsing, here is some documentation I wrote. The usecase was to read from a simple csv file and bulk to elasticsearch:

Considering this following log line:
1985-04-12T19:20:50, joao,26,engineer

.rb file:

version=2
rule=rsyslog:%date:char-to:,%,%name:char-to:,%,%age:char-to:,%,%job:word%

For more rules:
https://github.com/rsyslog/liblognorm/tree/master/rulebases
There is a binary called lognormalizer which checks if the rule is accurate.

rsyslog conf file:

module(load="imfile")
module(load="mmnormalize")
module(load="omelasticsearch")

input(type="imfile"
      File="/opt/log/*.log“
)

action(type="mmnormalize"
  rulebase="/opt/rsyslog/rule.rb"
  useRawMsg="on"
)

template(name="lumberjack" type="list"){
  property(name="$!all-json")
}

action(type="omelasticsearch"
  template="lumberjack" 
  searchIndex="test"
  searchType="events"
  server="localhost"
  serverport="9200"
  bulkmode="on"  # use the bulk API
  action.resumeretrycount="-1"  # retry indefinitely if Elasticsearch is unreachable
)

Rsyslog modules:
https://www.usenix.org/system/files/login/articles/06_lang-online.pdf


Hope this helps

**Comment by davidelang** [comment]
On Wed, 21 Aug 2019, aspyct wrote:

> Anyway, the only advice that I could give to other people who land here is: iterate on your rules using `lognormalizer -r rules.rb`, piece by piece.

very good advice, whenever I have a rule that I can't figure out what's 
happening, I put it in a rule file by itself and use lognormalizer to see what's 
happening
