### ISSUE TITLE
Float match but do not capture error

### ISSUE THREAD

**Issue by Amorik** [rsyslog/liblognorm#270]
When using float and designating it to not be captured the following error is displayed when compiling with lognormalizer:
>[root@myhost test]# lognormalizer -r number.rb
liblognorm error: rulebase file number.rb[2]: invalid param for float: name

os: 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
liblognorm: liblognorm5-2.0.4-1.el7.x86_64
rules file:
>version=2
rule=:%[{"type":"float", "name":"-"}]%

Update: this is also true for the type "number"

~Regards

**Comment by ajrpayne** [comment]
With 2.0.4 I have the same issue.

invalid param for date-rfc3164 name
invalid param for number: name 
invalid param for float: name

 %-:date-rfc3164%
%-:number%
%-:float%

**Comment by imqishi** [comment]
I have same issue
