### ISSUE TITLE
Does the whitespace type include tabs?

### ISSUE THREAD

**Issue by deoren** [rsyslog/liblognorm#287]
@rgerhards 

http://www.liblognorm.com/files/manual/configuration.html#whitespace

Does "whitespace" include tabs? I wasn't sure whether I should be expecting a match for one or multiple tabs or whether I need to use an ASCII escape sequence like \x011 to match each one.

I asked on the list, but I suspect that others are just as busy and haven't had time to respond. I know you're also very busy, so anything you're able to offer is appreciated. I'm happy to offer up a PR with additional coverage for that section if/when I ever figure out my problem.

Thanks.

**Comment by rgerhards** [comment]
I admit I don't know out of my head. Will try to check but need to get some missing imfile bit into the release.

**Comment by rgerhards** [comment]
Checked from the phone: the whitespace parser uses isspace(), so, yes, HT is whitespace: https://www.tutorialspoint.com/c_standard_library/c_function_isspace.htm
