### ISSUE TITLE
liblognorm for Java

### ISSUE THREAD

**Issue by solhuebner** [rsyslog/liblognorm#330]
I made it possible to use liblognorm from within Java (interface based on swig + custom extension).

Is there a general interest in that?

Please let me know and I will upload it to Github.

**Comment by otisg** [comment]
I think this would be awesome, @solhuebner !

**Comment by solhuebner** [comment]
Hi @otisg. thanks for your interest :) I will create a new repo. The one you mentioned is only used by me to make pull requests but I think this one will need a separate repo. Unfortunately, I am super busy this week but I will try to upload it on the weekend. If you need it more urgent I could send you some rough instructions on how to make it happen.

**Comment by otisg** [comment]
No rush.  Does your approach make it possible for somebody to add support for this to other languages and runtimes, like Node.js? (see https://github.com/rsyslog/liblognorm/issues/112)

**Comment by solhuebner** [comment]
@otisg Have a look at https://github.com/solhuebner/liblognormjava and let me know what to improve

**Comment by solhuebner** [comment]
> No rush. Does your approach make it possible for somebody to add support for this to other languages and runtimes, like Node.js? (see #112)

I think the issue here would be that spawning liblognorm (building the tree) is the most expensive operation. I think I have an example somewhere how to setup liblognorm as a REST service so that you could use it that way. Is that something of interest?

**Comment by solhuebner** [comment]
https://github.com/solhuebner/liblognormjava
