### ISSUE TITLE
add parser for python-style grouped regex

### ISSUE THREAD

**Issue by crackytsi** [rsyslog/liblognorm#62]
Hi,
Python supports to map a regex-selection to a specific attribute.
Sample here:
(?P<incoming_date>\w+\s+\d+\s+\d+:\d+:\d+)

So the result is filled into field "incoming_date".
This is -for my opinion- a quite nice way to map regex-result data to a field.
I would really like to have this functionatly also in liblognorm

Details can be found here:
http://www.regular-expressions.info/named.html

Chris

**Comment by rgerhards** [comment]
regexes are really contrary to the core ideas of liblognorm. While I gave in and permitted a basic regex functionality for those that really, really want it (it's disable by default), I do not want to promote regex any further. What we should really ask is which formats we need to support.
