### ISSUE TITLE
char-to and char-sep field types are not working as expected

### ISSUE THREAD

**Issue by khurlic** [rsyslog/liblognorm#63]
Im using rsyslog version 8.10.0 on centos 7 and liblognorm 1.1.1.

Im parsing the following text.
[error] 5522#0: *2 open() "/usr/share/nginx/html/test.html" failed (2: No such file or directory),

Im using the following rule to parse the text.
rule=nginx-error10:[%level:word% %pid:number%#%tid:number%: *%cid:number% %err_message:char-to:,%

I get these results when testing.
$ lognormalizer -r nginx.rule -e json < test.nginx 
{ "originalmsg": "[error] 5522#0: *2 open() \"\/usr\/share\/nginx\/html\/test.html\" failed (2: No such file or directory),", "unparsed-data": "," }

I've tried using the ascii hex characters instead or just a ',' and I've tried the field type of char-sep with both combinations. I am still receiving the unparsed-data error.

Can someone point me in the right direction?

Thanks.

**Comment by janmejay** [comment]
The char-to field doesn't consume trailing ','. You want to append a ',' to
the rule.

--
Regards,
Janmejay

PS: Please blame the typos in this mail on my phone's uncivilized soft
keyboard sporting it's not-so-smart-assist technology.

**Comment by khurlic** [comment]
That worked. Thanks for your help @janmejay
