### ISSUE TITLE
need a special fieldname to say "don't make this a sublevel"

### ISSUE THREAD

**Issue by davidelang** [rsyslog/liblognorm#65]
with new parsers that extract fieldnames from the data (name-value, json, descent, etc) there should be a way to say "don't make this another level down"

for example

instead of rule:=%json:json% that produces
{ "json": {json-from-data} }

there should be a way to make the output just be

{ json-from-data }

since '-' is already taken to mean "don't put this in the results" we need something else. I would suggest '+' or allow an empty fieldname ( %:json% )

note that with tokenize, this could produce garbage json, so I would say that this should only be allowed if the sub-pieces all define their own fieldname

so 
%+:tokenize:&:json%
would match
{"name": value}&{"name2":value2}
producing
{ "name": value, "name2":value2}
instead of
{"+":[{ "name": value}, {"name2":value2}]}

but {"name":value}&"name2"
would not match (probably with "unparsed-data"="&\"name2\"")

**Comment by janmejay** [comment]
How about:
%foo:merge:tokenize:&:json%

Which generates:
{"foo":{"name1": value, "name2": value2}}

The field type could be aliased to '+' in addition to 'merge' for
convenience.

Behavior of merge is to either merge elements of an array, or fail if they
are not merge-able.

--
Regards,
Janmejay

PS: Please blame the typos in this mail on my phone's uncivilized soft
keyboard sporting it's not-so-smart-assist technology.

**Comment by rgerhards** [comment]
Just fyi: i will add an that capability in the new json conf as well via a
regular parameter.

Sent from phone, thus brief.
Am 29.05.2015 02:29 schrieb "Janmejay Singh" <notifications@github.com>:

> How about:
> %foo:merge:tokenize:&:json%
>
> Which generates:
> {"foo":{"name1": value, "name2": value2}}
>
> The field type could be aliased to '+' in addition to 'merge' for
> convenience.
>
> Behavior of merge is to either merge elements of an array, or fail if they
> are not merge-able.
>
> --
> Regards,
> Janmejay
>
> PS: Please blame the typos in this mail on my phone's uncivilized soft
> keyboard sporting it's not-so-smart-assist technology.
>

**Comment by davidelang** [comment]
It's not just useful for json. Any of the types that can produce multiple 
elements can use this. The type "iptables" does this by default. def, tokenize, 
name-value-list, descent, all would benefit from this ability.

David Lang

**Comment by rgerhards** [comment]
2015-05-29 11:02 GMT+02:00 davidelang <notifications@github.com>:

> It's not just useful for json. Any of the types that can produce multiple
> elements can use this. The type "iptables" does this by default. def,
> tokenize,
> name-value-list, descent, all would benefit from this ability.
>

no, no, I talk about the *rule description language*. As part of the
lioblognorm  effort, I'll change it to JSON, so no longer need to have
these cryptic sequences. This also permits easy integration of features
like the one we talk about, as well as alternate text and even support for
automatted rule testing.

I don't have a draft sketch yet, but I need in any case shortly finish my
write-up on log formats and from there I will deduce parts of the new algo
and from there the exact config language to use.

Rainer

>
> David Lang
>
>
> On Fri, 29 May 2015, Rainer Gerhards wrote:
>
> > Just fyi: i will add an that capability in the new json conf as well via
> a
> > regular parameter.
> >
> > Sent from phone, thus brief.
> > Am 29.05.2015 02:29 schrieb "Janmejay Singh" <notifications@github.com>:
> >
> >> How about:
> >> %foo:merge:tokenize:&:json%
> >>
> >> Which generates:
> >> {"foo":{"name1": value, "name2": value2}}
> >>
> >> The field type could be aliased to '+' in addition to 'merge' for
> >> convenience.
> >>
> >> Behavior of merge is to either merge elements of an array, or fail if
> they
> >> are not merge-able.
> >>
> >> --
> >> Regards,
> >> Janmejay
> >>
> >> PS: Please blame the typos in this mail on my phone's uncivilized soft
> >> keyboard sporting it's not-so-smart-assist technology.
> >>

**Comment by rgerhards** [comment]
implemented in v2, see https://github.com/rsyslog/liblognorm/issues/95
