### ISSUE TITLE
testbench fails on freebsd

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/liblognorm#77]
sample: http://build.rsyslog.com:8010/builders/liblognormfreebsdslave/builds/4/steps/shell_3/logs/stdio

@janmejay could you have a look?

**Comment by janmejay** [comment]
Do we use bash or something else (csh)?

Can I get access to this machine?

On Tue, Jul 14, 2015 at 7:49 PM, Rainer Gerhards <notifications@github.com>
wrote:

> sample:
> http://build.rsyslog.com:8010/builders/liblognormfreebsdslave/builds/4/steps/shell_3/logs/stdio
>
> @janmejay <https://github.com/janmejay> could you have a look?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/liblognorm/issues/77>.
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment]
2015-07-14 18:18 GMT+02:00 Janmejay Singh <notifications@github.com>:

> Do we use bash or something else (csh)?
>
>
whatever is default on freebsd

Can I get access to this machine?
>

I need to talk to Andre, but I think we can do that at least temporarily.

Rainer

**Comment by janmejay** [comment]
I spawned a freebsd vm and have the problem reproduced.

On Tue, Jul 14, 2015 at 9:50 PM, Rainer Gerhards <notifications@github.com>
wrote:

> 2015-07-14 18:18 GMT+02:00 Janmejay Singh <notifications@github.com>:
>
> > Do we use bash or something else (csh)?
> >
> >
> whatever is default on freebsd
>
> Can I get access to this machine?
> >
>
> I need to talk to Andre, but I think we can do that at least temporarily.
>
> Rainer
>
>
> >
> > On Tue, Jul 14, 2015 at 7:49 PM, Rainer Gerhards <
> notifications@github.com
> > >
> > wrote:
> >
> > > sample:
> > >
> >
> http://build.rsyslog.com:8010/builders/liblognormfreebsdslave/builds/4/steps/shell_3/logs/stdio
> > >
> > > @janmejay <https://github.com/janmejay> could you have a look?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/rsyslog/liblognorm/issues/77>.
> > >
> >
> >
> >
> > --
> > Regards,
> > Janmejay
> > http://codehunk.wordpress.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/rsyslog/liblognorm/issues/77#issuecomment-121295106
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rsyslog/liblognorm/issues/77#issuecomment-121295560>.
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by janmejay** [comment]
Done: https://github.com/rsyslog/liblognorm/pull/79

Went home after reproducing the problem yesterday, hence the delay.

On Tue, Jul 14, 2015 at 10:08 PM, singh.janmejay <singh.janmejay@gmail.com>
wrote:

> I spawned a freebsd vm and have the problem reproduced.
>
> On Tue, Jul 14, 2015 at 9:50 PM, Rainer Gerhards <notifications@github.com
> > wrote:
>
>> 2015-07-14 18:18 GMT+02:00 Janmejay Singh <notifications@github.com>:
>>
>> > Do we use bash or something else (csh)?
>> >
>> >
>> whatever is default on freebsd
>>
>> Can I get access to this machine?
>> >
>>
>> I need to talk to Andre, but I think we can do that at least temporarily.
>>
>> Rainer
>>
>>
>> >
>> > On Tue, Jul 14, 2015 at 7:49 PM, Rainer Gerhards <
>> notifications@github.com
>> > >
>> > wrote:
>> >
>> > > sample:
>> > >
>> >
>> http://build.rsyslog.com:8010/builders/liblognormfreebsdslave/builds/4/steps/shell_3/logs/stdio
>> > >
>> > > @janmejay <https://github.com/janmejay> could you have a look?
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/rsyslog/liblognorm/issues/77>.
>> > >
>> >
>> >
>> >
>> > --
>> > Regards,
>> > Janmejay
>> > http://codehunk.wordpress.com
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/rsyslog/liblognorm/issues/77#issuecomment-121295106
>> >.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rsyslog/liblognorm/issues/77#issuecomment-121295560>.
>>
>
>
>
> --
> Regards,
> Janmejay
> http://codehunk.wordpress.com
>



-- 
Regards,
Janmejay
http://codehunk.wordpress.com

**Comment by rgerhards** [comment]
this is solved in 1.1.2.
