### ISSUE TITLE
Abstracted "ip" parser

### ISSUE THREAD

**Issue by sethhall** [rsyslog/liblognorm#85]
Would it be possible to create an abstracted "ip" parser that auto detects IPv4 and IPv6 addresses?  My experience is that most logs will put whatever address they're trying to communicate in the log and it makes it more difficult to write parsers if you want to support IPv4 and IPv6. (this ticket is related to the ipv6 parser patch you committed a few weeks ago)

**Comment by rgerhards** [comment]
Yes, isn't there even already an issue for this? Its just that I am
currently working on the lognorm engine so not sure if I can add this
tomorrow.

Sent from phone, thus brief.
Am 15.07.2015 19:00 schrieb "Seth Hall" <notifications@github.com>:

**Comment by sethhall** [comment]
Oh!  I apologize, I see it's ticket #71.  Closing!
